### ISSUE TITLE
Build Parser + AST from identfied tokens

### ISSUE THREAD

**Issue by paul3bin** [paul3bin/maths-interpreter#1]
- Build an abstract syntax tree from the list of tokens received.
- The AST will be used to identify syntax errors in the input

**Comment by cgaveyuea** [comment]
Good note, second sprint going well so far!

**Comment by paul3bin** [comment]
@cgaveyuea, @cst19hgu , @Aswin1121998 , @Soniyap151 
I added a feature to build AST and parse the input.
Further testing is required.
